pcd_map_server:
  ros__parameters:
    publish:
      pcd_map_topic: "pcd/map"
      map_frame_id: "map"
      pcd_dir: "/root/ros2_ws/src"
      pcd_file_name: "samhyun_sim.pcd"
      publish_on_start: true

    save:
      use_pcd_file: true
      input_cloud_topic: "Laser_map"
      output_dir: "/root/ros2_ws/src"
      output_file_name: "map"
      snapshot_timeout_sec: 3
      snapshot_transient_local: false

    save_grid:
      proj_z_min: 0.2
      proj_z_max: 1.5
      proj_resolution: 0.05
      proj_padding_m: 1.0
      proj_dilate_radius_px: 1
      ground_z_min: 0.0
      ground_z_max: 0.15
      obstacle_z_thresh: 0.20
      use_intensity: false
      intensity_thresh: 50.0
      yaml_occupied_thresh: 0.65
      yaml_free_thresh: 0.25
      yaml_mode: "trinary"
      yaml_negate: 0