pcd_map_server:
  ros__parameters:
    publish:
      pcd_map_topic: "pcd/map"
      map_frame_id: "map"
      pcd_dir: "/root/ros2_ws/src"
      pcd_file_name: "map_20251018_082600.pcd"
      publish_on_start: true

    save:
      input_cloud_topic: "Laser_map"
      output_dir: "/root/ros2_ws/src"
      output_file_name: "map"
      snapshot_timeout_sec: 3
      snapshot_transient_local: false